name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SWI-Prolog
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: swi-prolog
          
      - name: Run tests
        run: swipl -g run_tests -t halt monopoly.pl
